### ISSUE TITLE
Orientation of the gyroscope is positioned relative to the accelerometer

### ISSUE THREAD

**Issue by robbinhust** [emreemirfidan/EKF-Attitude-Estimation#1]
Hello, may I ask how the orientation of the gyroscope is positioned relative to the accelerometer? And what are the units of the accelerometer, gyroscope, and magnetometer? Thank you.

![image](https://github.com/emreemirfidan/EKF-Attitude-Estimation/assets/83688856/aecf98c1-4e85-480a-a85d-5f30dfeefbdf)

**Comment by emreemirfidan** [comment]
Hi, I used the coordinate system on pages 3 and 4 of this link: https://control.asu.edu/Classes/MMAE441/Aircraft/441Lecture9.pdf. Using this, you can find the correct direction of the gyroscope and accelerometer. The unit of accelerometer is m/s², the unit of gyroscope is rad/s and the unit of magnetometer is uT.
